# Generated by Django 5.1.1 on 2026-03-08 00:13

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "project_type",
                    models.CharField(
                        choices=[("original", "Original"), ("cover", "Cover")],
                        db_index=True,
                        default="original",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("seeking_lyrics", "Buscando Letrista"),
                            ("seeking_beat", "Buscando Productor"),
                            ("seeking_vocals", "Buscando Vocalista"),
                            ("in_review", "En Revisión"),
                            ("complete", "Completa"),
                            ("archived", "Archivada"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                ("allow_multiple_versions", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="accounts.genre",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="projects.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Contenido de la letra")),
                (
                    "language",
                    models.CharField(
                        default="es",
                        help_text="Código de idioma ISO 639-1",
                        max_length=10,
                    ),
                ),
                ("is_selected", models.BooleanField(db_index=True, default=False)),
                (
                    "original_artist",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Artista original (solo para covers)",
                        max_length=200,
                    ),
                ),
                (
                    "original_song",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Canción original (solo para covers)",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lyrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lyrics",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Letra",
                "verbose_name_plural": "Letras",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Beat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        help_text="Archivo de audio original subido por el usuario",
                        upload_to=apps.projects.models.audio_upload_path,
                    ),
                ),
                (
                    "streaming_file",
                    models.FileField(
                        blank=True,
                        help_text="Archivo MP3 128kbps generado para streaming",
                        upload_to=apps.projects.models.streaming_upload_path,
                    ),
                ),
                (
                    "audio_format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Formato del archivo original (mp3, wav, flac...)",
                        max_length=10,
                    ),
                ),
                (
                    "audio_duration",
                    models.DurationField(
                        blank=True, help_text="Duración del audio", null=True
                    ),
                ),
                (
                    "audio_bitrate",
                    models.IntegerField(
                        blank=True, help_text="Bitrate en kbps", null=True
                    ),
                ),
                (
                    "audio_sample_rate",
                    models.IntegerField(
                        blank=True, help_text="Sample rate en Hz", null=True
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="Tamaño del archivo en bytes"
                    ),
                ),
                (
                    "waveform_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos JSON de la forma de onda para Wavesurfer.js",
                        null=True,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("ready", "Listo"),
                            ("failed", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Estado del procesamiento async",
                        max_length=20,
                    ),
                ),
                (
                    "bpm",
                    models.PositiveIntegerField(
                        blank=True, help_text="Beats por minuto", null=True
                    ),
                ),
                (
                    "key_signature",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tonalidad (ej. C#m, Fmaj)",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_selected", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beats",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beat",
                "verbose_name_plural": "Beats",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VocalTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        help_text="Archivo de audio original subido por el usuario",
                        upload_to=apps.projects.models.audio_upload_path,
                    ),
                ),
                (
                    "streaming_file",
                    models.FileField(
                        blank=True,
                        help_text="Archivo MP3 128kbps generado para streaming",
                        upload_to=apps.projects.models.streaming_upload_path,
                    ),
                ),
                (
                    "audio_format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Formato del archivo original (mp3, wav, flac...)",
                        max_length=10,
                    ),
                ),
                (
                    "audio_duration",
                    models.DurationField(
                        blank=True, help_text="Duración del audio", null=True
                    ),
                ),
                (
                    "audio_bitrate",
                    models.IntegerField(
                        blank=True, help_text="Bitrate en kbps", null=True
                    ),
                ),
                (
                    "audio_sample_rate",
                    models.IntegerField(
                        blank=True, help_text="Sample rate en Hz", null=True
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="Tamaño del archivo en bytes"
                    ),
                ),
                (
                    "waveform_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos JSON de la forma de onda para Wavesurfer.js",
                        null=True,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("ready", "Listo"),
                            ("failed", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Estado del procesamiento async",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_selected", models.BooleanField(db_index=True, default=False)),
                (
                    "version_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Número de versión de la pista vocal"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocal_tracks",
                        to="projects.project",
                    ),
                ),
                (
                    "vocalist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocal_tracks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pista Vocal",
                "verbose_name_plural": "Pistas Vocales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinalMix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        help_text="Archivo de audio original subido por el usuario",
                        upload_to=apps.projects.models.audio_upload_path,
                    ),
                ),
                (
                    "streaming_file",
                    models.FileField(
                        blank=True,
                        help_text="Archivo MP3 128kbps generado para streaming",
                        upload_to=apps.projects.models.streaming_upload_path,
                    ),
                ),
                (
                    "audio_format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Formato del archivo original (mp3, wav, flac...)",
                        max_length=10,
                    ),
                ),
                (
                    "audio_duration",
                    models.DurationField(
                        blank=True, help_text="Duración del audio", null=True
                    ),
                ),
                (
                    "audio_bitrate",
                    models.IntegerField(
                        blank=True, help_text="Bitrate en kbps", null=True
                    ),
                ),
                (
                    "audio_sample_rate",
                    models.IntegerField(
                        blank=True, help_text="Sample rate en Hz", null=True
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="Tamaño del archivo en bytes"
                    ),
                ),
                (
                    "waveform_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos JSON de la forma de onda para Wavesurfer.js",
                        null=True,
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("ready", "Listo"),
                            ("failed", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Estado del procesamiento async",
                        max_length=20,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de portada del mix final",
                        null=True,
                        upload_to="covers/%Y/%m/",
                    ),
                ),
                ("play_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="final_mixes",
                        to="projects.beat",
                    ),
                ),
                (
                    "lyrics",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="final_mixes",
                        to="projects.lyrics",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_mix",
                        to="projects.project",
                    ),
                ),
                (
                    "vocal_track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="final_mixes",
                        to="projects.vocaltrack",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mix Final",
                "verbose_name_plural": "Mixes Finales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "project_type"], name="projects_pr_status_b41d0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_public", "status"], name="projects_pr_is_publ_8872db_idx"
            ),
        ),
    ]
