# Generated by Django 5.1.1 on 2026-03-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beat",
            name="flag_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Contador denormalizado de flags activos"
            ),
        ),
        migrations.AddField(
            model_name="beat",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="beat",
            name="hidden_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="beat",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Oculto por moderación automática o manual",
            ),
        ),
        migrations.AddField(
            model_name="finalmix",
            name="flag_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Contador denormalizado de flags activos"
            ),
        ),
        migrations.AddField(
            model_name="finalmix",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="finalmix",
            name="hidden_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="finalmix",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Oculto por moderación automática o manual",
            ),
        ),
        migrations.AddField(
            model_name="lyrics",
            name="flag_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Contador denormalizado de flags activos"
            ),
        ),
        migrations.AddField(
            model_name="lyrics",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lyrics",
            name="hidden_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="lyrics",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Oculto por moderación automática o manual",
            ),
        ),
        migrations.AddField(
            model_name="vocaltrack",
            name="flag_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Contador denormalizado de flags activos"
            ),
        ),
        migrations.AddField(
            model_name="vocaltrack",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vocaltrack",
            name="hidden_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="vocaltrack",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Oculto por moderación automática o manual",
            ),
        ),
    ]
