# Generated by Django 5.1.1 on 2026-03-08 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReputationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Puntos ganados o perdidos (puede ser negativo)"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Motivo del cambio de puntuación", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reputation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Reputación",
                "verbose_name_plural": "Logs de Reputación",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RankingCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ranking_type",
                    models.CharField(
                        db_index=True,
                        help_text="Tipo de ranking (global, by_role, by_genre, covers)",
                        max_length=50,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("all_time", "Todo el Tiempo"),
                        ],
                        db_index=True,
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "entries",
                    models.JSONField(
                        default=list, help_text="Entradas del ranking en formato JSON"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Filtro de género (null = todos los géneros)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rankings",
                        to="accounts.genre",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Filtro de rol (null = todos los roles)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rankings",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caché de Ranking",
                "verbose_name_plural": "Cachés de Rankings",
                "ordering": ["-calculated_at"],
                "unique_together": {("ranking_type", "period", "genre", "role")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(
                        db_index=True, help_text="ID del objeto votado"
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("upvote", "Voto Positivo"),
                            ("downvote", "Voto Negativo"),
                        ],
                        default="upvote",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Tipo de contenido votado (FinalMix, Lyrics, Beat, VocalTrack)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto",
                "verbose_name_plural": "Votos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="rankings_vo_content_ccff59_idx",
                    )
                ],
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
    ]
