# Generated by Django 5.1.1 on 2026-03-11 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(db_index=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("copyright", "Infracción de derechos de autor"),
                            ("plagiarism", "Plagio de contenido"),
                            ("offensive", "Contenido ofensivo o inapropiado"),
                            ("spam", "Spam o contenido no relacionado"),
                            ("other", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción opcional del problema",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente de revisión"),
                            ("reviewing", "En revisión"),
                            ("upheld", "Reporte confirmado"),
                            ("dismissed", "Reporte descartado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("remove", "Contenido removido"),
                            ("hide", "Contenido oculto temporalmente"),
                            ("dismiss", "Reporte descartado"),
                            ("warn", "Advertencia al usuario"),
                            ("ban", "Usuario suspendido"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Notas internas del moderador"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="moderation.flag",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Acción de Moderación",
                "verbose_name_plural": "Acciones de Moderación",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="moderation__content_a8ab86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(fields=["status"], name="moderation__status_747f1d_idx"),
        ),
        migrations.AddConstraint(
            model_name="flag",
            constraint=models.UniqueConstraint(
                fields=("reporter", "content_type", "object_id"),
                name="unique_flag_per_user_per_content",
            ),
        ),
    ]
