# Generated by Django 5.1.1 on 2026-03-08 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioProcessingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveBigIntegerField(help_text="ID del objeto de audio"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID de la tarea Celery",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "En Cola"),
                            ("running", "Ejecutando"),
                            ("success", "Exitoso"),
                            ("failure", "Fallido"),
                            ("retrying", "Reintentando"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Mensaje de error si el procesamiento falló",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Número de intentos de procesamiento"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Tipo de modelo de audio (Beat, VocalTrack, FinalMix)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de Procesamiento",
                "verbose_name_plural": "Tareas de Procesamiento",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audio_audio_content_7b8b31_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="audio_audio_status_1cd1e1_idx",
                    ),
                ],
            },
        ),
    ]
