# Generated by Django 5.1.1 on 2026-03-08 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("vote_received", "Voto Recibido"),
                            ("contribution_selected", "Contribución Seleccionada"),
                            ("project_complete", "Proyecto Completado"),
                            ("new_contribution", "Nueva Contribución"),
                            ("badge_awarded", "Insignia Obtenida"),
                            ("top_ranking", "Top en Rankings"),
                            ("mention", "Mención"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL relativa a la que lleva la notificación",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Usuario que recibe la notificación",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que generó la notificación (null para notificaciones del sistema)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="notificatio_recipie_4e3567_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="notificatio_recipie_f39341_idx",
                    ),
                ],
            },
        ),
    ]
